### ISSUE TITLE
滚轮滑动特别慢，很折磨

### ISSUE THREAD

**Issue by miaotouy** [BLACKujira/SekaiTools#1]
不知道是不是和屏幕分辨率有关，我的显示器是4k的150%缩放，希望添加滚动条可以直接拖拽滚动

**Comment by BLACKujira** [comment]
感谢您的反馈，这个问题似乎是由于设计时没有调整卷轴速度导致的，已计划修复此问题。
在当前版本中，可以暂时采用按住卷轴区域拖拽的方式进行滚动以避免此问题。
